/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javachallenges;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("helloworld");
        return true;
    }
}
